
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: highcapitalchatbotdb
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: